/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSupervisorIndexRouteImport } from './routes/_authenticated/supervisor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSupervisorRiskRouteImport } from './routes/_authenticated/supervisor.risk'
import { Route as AuthenticatedSupervisorReviewsRouteImport } from './routes/_authenticated/supervisor.reviews'
import { Route as AuthenticatedSupervisorReportsRouteImport } from './routes/_authenticated/supervisor.reports'
import { Route as AuthenticatedSupervisorAnalyticsRouteImport } from './routes/_authenticated/supervisor.analytics'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminEstablishmentsRouteImport } from './routes/_authenticated/admin.establishments'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin.assignments'
import { Route as AuthenticatedSupervisorInspectionIdRouteImport } from './routes/_authenticated/supervisor.inspection.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorIndexRoute =
  AuthenticatedSupervisorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSupervisorRiskRoute =
  AuthenticatedSupervisorRiskRouteImport.update({
    id: '/risk',
    path: '/risk',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorReviewsRoute =
  AuthenticatedSupervisorReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorReportsRoute =
  AuthenticatedSupervisorReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorAnalyticsRoute =
  AuthenticatedSupervisorAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstablishmentsRoute =
  AuthenticatedAdminEstablishmentsRouteImport.update({
    id: '/establishments',
    path: '/establishments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSupervisorInspectionIdRoute =
  AuthenticatedSupervisorInspectionIdRouteImport.update({
    id: '/inspection/$id',
    path: '/inspection/$id',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/establishments': typeof AuthenticatedAdminEstablishmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/supervisor/analytics': typeof AuthenticatedSupervisorAnalyticsRoute
  '/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/supervisor/reviews': typeof AuthenticatedSupervisorReviewsRoute
  '/supervisor/risk': typeof AuthenticatedSupervisorRiskRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/supervisor/inspection/$id': typeof AuthenticatedSupervisorInspectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/establishments': typeof AuthenticatedAdminEstablishmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/supervisor/analytics': typeof AuthenticatedSupervisorAnalyticsRoute
  '/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/supervisor/reviews': typeof AuthenticatedSupervisorReviewsRoute
  '/supervisor/risk': typeof AuthenticatedSupervisorRiskRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/supervisor': typeof AuthenticatedSupervisorIndexRoute
  '/supervisor/inspection/$id': typeof AuthenticatedSupervisorInspectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/establishments': typeof AuthenticatedAdminEstablishmentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/supervisor/analytics': typeof AuthenticatedSupervisorAnalyticsRoute
  '/_authenticated/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/_authenticated/supervisor/reviews': typeof AuthenticatedSupervisorReviewsRoute
  '/_authenticated/supervisor/risk': typeof AuthenticatedSupervisorRiskRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/_authenticated/supervisor/inspection/$id': typeof AuthenticatedSupervisorInspectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/supervisor'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/establishments'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/supervisor/analytics'
    | '/supervisor/reports'
    | '/supervisor/reviews'
    | '/supervisor/risk'
    | '/admin/'
    | '/supervisor/'
    | '/supervisor/inspection/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/establishments'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/supervisor/analytics'
    | '/supervisor/reports'
    | '/supervisor/reviews'
    | '/supervisor/risk'
    | '/admin'
    | '/supervisor'
    | '/supervisor/inspection/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/supervisor'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/establishments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/users'
    | '/_authenticated/supervisor/analytics'
    | '/_authenticated/supervisor/reports'
    | '/_authenticated/supervisor/reviews'
    | '/_authenticated/supervisor/risk'
    | '/_authenticated/admin/'
    | '/_authenticated/supervisor/'
    | '/_authenticated/supervisor/inspection/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/': {
      id: '/_authenticated/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AuthenticatedSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/supervisor/risk': {
      id: '/_authenticated/supervisor/risk'
      path: '/risk'
      fullPath: '/supervisor/risk'
      preLoaderRoute: typeof AuthenticatedSupervisorRiskRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/reviews': {
      id: '/_authenticated/supervisor/reviews'
      path: '/reviews'
      fullPath: '/supervisor/reviews'
      preLoaderRoute: typeof AuthenticatedSupervisorReviewsRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/reports': {
      id: '/_authenticated/supervisor/reports'
      path: '/reports'
      fullPath: '/supervisor/reports'
      preLoaderRoute: typeof AuthenticatedSupervisorReportsRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/analytics': {
      id: '/_authenticated/supervisor/analytics'
      path: '/analytics'
      fullPath: '/supervisor/analytics'
      preLoaderRoute: typeof AuthenticatedSupervisorAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/establishments': {
      id: '/_authenticated/admin/establishments'
      path: '/establishments'
      fullPath: '/admin/establishments'
      preLoaderRoute: typeof AuthenticatedAdminEstablishmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/supervisor/inspection/$id': {
      id: '/_authenticated/supervisor/inspection/$id'
      path: '/inspection/$id'
      fullPath: '/supervisor/inspection/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorInspectionIdRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminEstablishmentsRoute: typeof AuthenticatedAdminEstablishmentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminEstablishmentsRoute: AuthenticatedAdminEstablishmentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSupervisorRouteChildren {
  AuthenticatedSupervisorAnalyticsRoute: typeof AuthenticatedSupervisorAnalyticsRoute
  AuthenticatedSupervisorReportsRoute: typeof AuthenticatedSupervisorReportsRoute
  AuthenticatedSupervisorReviewsRoute: typeof AuthenticatedSupervisorReviewsRoute
  AuthenticatedSupervisorRiskRoute: typeof AuthenticatedSupervisorRiskRoute
  AuthenticatedSupervisorIndexRoute: typeof AuthenticatedSupervisorIndexRoute
  AuthenticatedSupervisorInspectionIdRoute: typeof AuthenticatedSupervisorInspectionIdRoute
}

const AuthenticatedSupervisorRouteChildren: AuthenticatedSupervisorRouteChildren =
  {
    AuthenticatedSupervisorAnalyticsRoute:
      AuthenticatedSupervisorAnalyticsRoute,
    AuthenticatedSupervisorReportsRoute: AuthenticatedSupervisorReportsRoute,
    AuthenticatedSupervisorReviewsRoute: AuthenticatedSupervisorReviewsRoute,
    AuthenticatedSupervisorRiskRoute: AuthenticatedSupervisorRiskRoute,
    AuthenticatedSupervisorIndexRoute: AuthenticatedSupervisorIndexRoute,
    AuthenticatedSupervisorInspectionIdRoute:
      AuthenticatedSupervisorInspectionIdRoute,
  }

const AuthenticatedSupervisorRouteWithChildren =
  AuthenticatedSupervisorRoute._addFileChildren(
    AuthenticatedSupervisorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
