// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    console.log("[requireSupabaseAuth] ✦ middleware entered");
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      console.error("[requireSupabaseAuth] ✘ No request headers available");
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    console.log("[requireSupabaseAuth] Authorization header present:", !!authHeader);

    if (!authHeader) {
      console.error("[requireSupabaseAuth] ✘ No Authorization header — attachSupabaseAuth may not have run, or session was missing at call time");
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      console.error("[requireSupabaseAuth] ✘ Authorization header does not start with 'Bearer '");
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      console.error("[requireSupabaseAuth] ✘ Token is empty string after stripping 'Bearer '");
      throw new Error('Unauthorized: No token provided');
    }

    const tokenParts = token.split('.');
    console.log("[requireSupabaseAuth] Token segment count:", tokenParts.length, "(expected 3 for JWT)");
    if (tokenParts.length !== 3) {
      console.error("[requireSupabaseAuth] ✘ Token is not a valid 3-part JWT — got", tokenParts.length, "parts");
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    console.log("[requireSupabaseAuth] Calling getClaims to validate token...");
    const { data, error } = await supabase.auth.getClaims(token);
    console.log("[requireSupabaseAuth] getClaims result — claims present:", !!data?.claims, "| error:", error ?? null);

    if (error || !data?.claims) {
      console.error("[requireSupabaseAuth] ✘ getClaims failed:", error?.message ?? "no claims returned");
      throw new Error('Unauthorized: Invalid token');
    }

    console.log("[requireSupabaseAuth] ✔ Token valid — userId (sub):", data.claims.sub, "| role claim:", (data.claims as any).role ?? "(none)");

    if (!data.claims.sub) {
      console.error("[requireSupabaseAuth] ✘ JWT has no 'sub' claim");
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
